{
 "title": "Device_Health_XE",
 "description": "Cisco IOS XE and the Catalyst 9300 switch using the gRPC Dial-Out Model-Driven Telemetry interface to provide basic health and interface monitoring capabilities",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "SOURCE",
    "query": "show tag values with key = \"source\""
   },
   {
    "name": "NAME",
    "query": "show tag values with key = \"name\""
   },
   {
    "name": "VRF",
    "query": "show tag values with key = \"vrf\""
   }
  ]
 },
 "panels": [
  {
   "title": "Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Version",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "Cisco-IOS-XE-native:native",
       "select": [
        [
         { "params": [ "version" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Last Boot",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 2, "y": 1 },
     "format": "dateTimeAsIso",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "openconfig-system:system/state",
       "select": [
        [
         { "params": [ "boot_time" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "* 1000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" }
       ]
      }
     ]
    },
    {
     "title": "Fan Speed",
     "type": "bargauge",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "rpm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "[[tag_name]]",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "openconfig-platform:components/component/fan/state",
       "select": [
        [
         { "params": [ "openconfig_platform_fan:speed" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "alias": "[[tag_name]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "openconfig-platform:components/component/state/temperature",
       "select": [
        [
         { "params": [ "instant" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" }
       ]
      }
     ]
    },
    {
     "title": "Power",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
     "yaxes": [
      { "format": "watt" }
     ],
     "targets": [
      {
       "alias": "[[tag_name]] $col",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XE-poe-oper:poe-oper-data/poe-switch",
       "select": [
        [
         { "params": [ "available_power" ], "type": "field" }
        ],
        [
         { "params": [ "consumed_system_power" ], "type": "field" }
        ],
        [
         { "params": [ "power_budget" ], "type": "field" }
        ],
        [
         { "params": [ "power_allocated" ], "type": "field" }
        ],
        [
         { "params": [ "consumed_poe_power" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" }
       ]
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "alias": "[[tag_name]] $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Cisco-IOS-XE-memory-oper:memory-statistics/memory-statistic",
       "select": [
        [
         { "params": [ "free_memory" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "free" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "Processor" }
       ]
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 4 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "alias": "[[tag_name]] $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Cisco-IOS-XE-memory-oper:memory-statistics/memory-statistic",
       "select": [
        [
         { "params": [ "used_memory" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "used" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "Processor" }
       ]
      }
     ]
    },
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Cisco-IOS-XE-process-cpu-oper:cpu-usage/cpu-utilization",
       "select": [
        [
         { "params": [ "five_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Five Seconds" ], "type": "alias" }
        ],
        [
         { "params": [ "one_minute" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "One Minute" ], "type": "alias" }
        ],
        [
         { "params": [ "five_minutes" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Five Minutes" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" }
       ]
      }
     ]
    },
    {
     "title": "CDP ",
     "type": "table",
     "gridPos": { "h": 10, "w": 16, "x": 8, "y": 11 },
     "targets": [
      {
       "measurement": "Cisco-IOS-XE-cdp-oper:cdp-neighbor-details/cdp-neighbor-detail",
       "select": [
        [
         { "params": [ "device_name" ], "type": "field" }
        ],
        [
         { "params": [ "ip_address" ], "type": "field" }
        ],
        [
         { "params": [ "local_intf_name" ], "type": "field" }
        ],
        [
         { "params": [ "mgmt_address" ], "type": "field" }
        ],
        [
         { "params": [ "port_id" ], "type": "field" }
        ],
        [
         { "params": [ "platform_name" ], "type": "field" }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "IP MAC ARP - Client Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "ARP",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "alias": "$col",
       "measurement": "Cisco-IOS-XE-arp-oper:arp-data/arp-vrf",
       "query": "SELECT  *,last(\"arp_oper/hardware\") AS \"arp_oper/interface\" FROM \"Cisco-IOS-XE-arp-oper:arp-data/arp-vrf\" WHERE (\"source\" =~ /^$SOURCE$/ AND \"vrf\" =~ /^$VRF$/) AND $timeFilter GROUP BY *",
       "select": [
        [
         { "params": [ "arp_oper/address" ], "type": "field" }
        ],
        [
         { "params": [ "arp_oper/enctype" ], "type": "field" }
        ],
        [
         { "params": [ "arp_oper/hardware" ], "type": "field" }
        ],
        [
         { "params": [ "arp_oper/hwtype" ], "type": "field" }
        ],
        [
         { "params": [ "arp_oper/interface" ], "type": "field" }
        ],
        [
         { "params": [ "arp_oper/mode" ], "type": "field" }
        ],
        [
         { "params": [ "arp_oper/time" ], "type": "field" }
        ],
        [
         { "params": [ "arp_oper/type" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" },
        { "condition": "AND", "key": "vrf", "operator": "=~", "value": "/^$VRF$/" }
       ]
      }
     ]
    },
    {
     "title": "MAC Address Tab Mapping",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "alias": "$col",
       "measurement": "Cisco-IOS-XE-matm-oper:matm-oper-data/matm-table",
       "query": "SELECT *,last(\"matm_mac_entry/mac\") AS \"matm_mac_entry/port\" FROM \"Cisco-IOS-XE-matm-oper:matm-oper-data/matm-table\" WHERE (\"source\" =~ /^$SOURCE$/) AND $timeFilter GROUP BY *",
       "select": [
        [
         { "params": [ "matm_mac_entry/mac" ], "type": "field" }
        ],
        [
         { "params": [ "matm_mac_entry/mat_addr_type" ], "type": "field" }
        ],
        [
         { "params": [ "matm_mac_entry/port" ], "type": "field" }
        ],
        [
         { "params": [ "matm_mac_entry/table_type" ], "type": "field" }
        ],
        [
         { "params": [ "matm_mac_entry/vlan_id_number" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC MDT Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "MDT",
     "type": "table",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "alias": "$col",
       "measurement": "Cisco-IOS-XE-mdt-oper:mdt-oper-data/mdt-subscriptions",
       "query": "SELECT *, last(\"base/xpath\") AS \"base/xpath\" FROM \"Cisco-IOS-XE-mdt-oper:mdt-oper-data/mdt-subscriptions\" WHERE (\"source\" =~ /^$SOURCE$/) AND $timeFilter GROUP BY *",
       "select": [
        [
         { "params": [ "base/period" ], "type": "field" }
        ],
        [
         { "params": [ "state" ], "type": "field" }
        ],
        [
         { "params": [ "base/stream" ], "type": "field" }
        ],
        [
         { "params": [ "base/encoding" ], "type": "field" }
        ],
        [
         { "params": [ "type" ], "type": "field" }
        ],
        [
         { "params": [ "base/xpath" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Interface - Cisco Native - Charts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interface tx-kbps",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "Kbits" }
     ],
     "targets": [
      {
       "alias": "[[tag_name]]",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Cisco-IOS-XE-interfaces-oper:interfaces/interface",
       "select": [
        [
         { "params": [ "statistics/tx_kbps" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$NAME$/" },
        { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$SOURCE$/" }
       ]
      }
     ]
    },
    {
     "title": "Interface rx-kbps",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "Kbits" }
     ],
     "targets": [
      {
       "alias": "[[tag_name]]",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Cisco-IOS-XE-interfaces-oper:interfaces/interface",
       "select": [
        [
         { "params": [ "statistics/rx_kbps" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$NAME$/" },
        { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$SOURCE$/" }
       ]
      }
     ]
    },
    {
     "title": "Device Traffic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "Kbits" }
     ],
     "targets": [
      {
       "alias": "$col",
       "measurement": "Cisco-IOS-XE-interfaces-oper:interfaces/interface",
       "select": [
        [
         { "params": [ "statistics/rx_kbps" ], "type": "field" },
         { "params": [ "10s" ], "type": "non_negative_derivative" },
         { "params": [ "rx kbps" ], "type": "alias" }
        ],
        [
         { "params": [ "statistics/tx_kbps" ], "type": "field" },
         { "params": [ "10s" ], "type": "non_negative_derivative" },
         { "params": [ "tx kbps" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$NAME$/" },
        { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$SOURCE$/" }
       ]
      }
     ]
    },
    {
     "title": "Packet Counters",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "[[tag_name]]",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Cisco-IOS-XE-interfaces-oper:interfaces/interface",
       "select": [
        [
         { "params": [ "statistics/rx_pps" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$NAME$/" },
        { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$SOURCE$/" }
       ]
      },
      {
       "alias": "[[tag_name]]",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Cisco-IOS-XE-interfaces-oper:interfaces/interface",
       "select": [
        [
         { "params": [ "statistics/tx_pps" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$NAME$/" },
        { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$SOURCE$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Interfaces - Cisco Native - Data Table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interface Stats",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "alias": "$col",
       "measurement": "Cisco-IOS-XE-interfaces-oper:interfaces/interface",
       "query": "SELECT *,last(\"last_change\") FROM \"Cisco-IOS-XE-interfaces-oper:interfaces/interface\" WHERE (\"source\" =~ /^$SOURCE$/ AND \"name\" =~ /^$NAME$/) AND $timeFilter GROUP BY *",
       "select": [
        [
         { "params": [ "vrf" ], "type": "field" }
        ],
        [
         { "params": [ "admin_status" ], "type": "field" }
        ],
        [
         { "params": [ "interface_type" ], "type": "field" }
        ],
        [
         { "params": [ "oper_status" ], "type": "field" }
        ],
        [
         { "params": [ "phys_address" ], "type": "field" }
        ],
        [
         { "params": [ "description" ], "type": "field" }
        ],
        [
         { "params": [ "mtu" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$NAME$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "IETF Interfaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "IETF Interfaces",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "measurement": "ietf-interfaces:interfaces-state/interface",
       "query": "SELECT *,last(\"phys_address\") FROM \"ietf-interfaces:interfaces-state/interface\" WHERE (\"source\" =~ /^$SOURCE$/ AND \"name\" =~ /^$NAME$/) AND $timeFilter GROUP BY *",
       "select": [
        [
         { "params": [ "statistics/in_octets" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$NAME$/" }
       ]
      }
     ]
    },
    {
     "title": "IETF out_octets",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "[[tag_name]]",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ietf-interfaces:interfaces-state/interface",
       "select": [
        [
         { "params": [ "statistics/out_octets" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$NAME$/" },
        { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$SOURCE$/" }
       ]
      }
     ]
    },
    {
     "title": "IETF in_octets",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "[[tag_name]]",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ietf-interfaces:interfaces-state/interface",
       "select": [
        [
         { "params": [ "statistics/in_octets" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$NAME$/" },
        { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$SOURCE$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Interfaces - OpenConfig",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "OpenConfig Interfaces",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "measurement": "openconfig-interfaces:interfaces/interface/state/counters",
       "query": "SELECT *,last(\"last_clear\") FROM \"openconfig-interfaces:interfaces/interface/state/counters\" WHERE (\"source\" =~ /^$SOURCE$/ AND \"name\" =~ /^$NAME$/) AND $timeFilter GROUP BY *",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$NAME$/" }
       ]
      }
     ]
    },
    {
     "title": "Bytes In (OC)",
     "type": "graph",
     "gridPos": { "h": 17, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "[[tag_name]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "openconfig-interfaces:interfaces/interface/state/counters",
       "select": [
        [
         { "params": [ "in_octets" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$NAME$/" }
       ]
      }
     ]
    },
    {
     "title": "Bytes Out (OC)",
     "type": "graph",
     "gridPos": { "h": 17, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "[[tag_name]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "openconfig-interfaces:interfaces/interface/state/counters",
       "select": [
        [
         { "params": [ "out_octets" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$NAME$/" }
       ]
      }
     ]
    },
    {
     "title": "Total Device Bytes In/Out (OC)",
     "type": "graph",
     "gridPos": { "h": 18, "w": 8, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "openconfig-interfaces:interfaces/interface/state/counters",
       "select": [
        [
         { "params": [ "in_octets" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" },
         { "params": [ "Ingress Bytes" ], "type": "alias" }
        ],
        [
         { "params": [ "out_octets" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" },
         { "params": [ "Egress Bytes" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" }
       ]
      }
     ]
    },
    {
     "title": "Packets (OC)",
     "type": "graph",
     "gridPos": { "h": 18, "w": 16, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "alias": "[[tag_name]] in",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "openconfig-interfaces:interfaces/interface/state/counters",
       "select": [
        [
         { "params": [ "in_unicast_pkts" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$NAME$/" }
       ]
      },
      {
       "alias": "[[tag_name]] out",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "openconfig-interfaces:interfaces/interface/state/counters",
       "select": [
        [
         { "params": [ "out_unicast_pkts" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$SOURCE$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$NAME$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}